{

    "description": "add from node",
    "entrypoint": "AnyJob.Internal.Demo.Concat,AnyJob.Internal.Demo.dll",
    "kind": "internal",
    "inputs": {
        "a": {
            "type": "string"
        },
        "b": {
            "type": "string"
        }
    },
    "output": {
        "type": "string"
    }
}