{

    "description": "hello action",
    "entrypoint": "AnyJob.Internal.Demo.Hello,AnyJob.Internal.Demo.dll",
    "kind": "internal",
    "inputs": {
        "name": {
            "type": "string"
        }
    },
    "output": {
        "type": "null"
    }
}