{

    "description": "hello action",
    "entrypoint": "AnyJob.Runner.Internal.IntegrationTest.Actions.Hello,AnyJob.Runner.Internal.IntegrationTest",
    "kind": "internal",
    "inputs": {
        "name": {
            "type": "string"
        }
    },
    "output": {
        "type": "null"
    }
}