{
    "enabled": true,
    "description": "merge complex objects",
    "entrypoint": "AnyJob.Internal.Demo.Merge,AnyJob.Internal.Demo.dll",
    "kind": "internal",
    "inputs": {
        "persons": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": { "type": "number" },
                    "name": { "type": "string" }
                }
            }
        },
        "other": {
            "type": "object",
            "properties": {
                "id": { "type": "number" },
                "name": { "type": "string" }
            }
        }
    },
    "output": {
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
                "id": { "type": "number" },
                "name": { "type": "string" }
            }
        }
    }
}