{
    "enabled": true,
    "entrypoint": "ping.json",
    "kind": "app",
    "inputs": {
        "host": {
            "type": "string"
        },
        "count": {
            "type": "number"
        }
    },
    "output": {
        "type": "string"
    }
}