{
    "enabled": true,
    "description": "add from node",
    "entrypoint": "AnyJob.Java.Demo-1.0.jar/demo.Instance.concat",
    "kind": "java",
    "inputs": {
        "a": {
            "type": "string"
        },Í
        "b": {
            "type": "string"
        }
    },
    "output": {
        "type": "string"
    }
}