{

    "description": "hello action",
    "entrypoint": "demo.Static,hello",
    "kind": "java",
    "inputs": {
        "name": {
            "type": "string"
        }
    },
    "output": {
        "type": "null"
    }
}