{
    "enabled": true,
    "description": "add from node",
    "entrypoint": "AnyJob.Runner.Workflow.Actions.Add,AnyJob.Runner.Workflow.UnitTest",
    "kind": "assembly",
    "inputs": {
        "num1": {
            "type": "number"
        },
        "num2": {
            "type": "number"
        }
    },
    "output": {
        "type": "number"
    }
}