{

    "description": "concat from node",
    "entrypoint": "concat,run",
    "kind": "python",
    "inputs": {
        "a": {
            "type": "string",
            "must": true
        },
        "b": {
            "type": "string"
        }
    },
    "output": {
        "type": "string"
    }
}