{

    "description": "add from node",
    "entrypoint": "AnyJob.Advance.Demo.Concat,AnyJob.Advance.Demo.dll",
    "kind": "advance",
    "inputs": {
        "a": {
            "type": "string"
        },
        "b": {
            "type": "string"
        }
    },
    "output": {
        "type": "string"
    }
}