{

    "description": "add from node",
    "entrypoint": "AnyJob.Advance.Demo.Add,AnyJob.Advance.Demo.dll",
    "kind": "advance",
    "inputs": {
        "num1": {
            "type": "number"
        },
        "num2": {
            "type": "number"
        }
    },
    "output": {
        "type": "number"
    }
}