{

    "description": "hello action",
    "entrypoint": "AnyJob.Advance.Demo.Hello,AnyJob.Advance.Demo.dll",
    "kind": "advance",
    "inputs": {
        "name": {
            "type": "string"
        }
    },
    "output": {
        "type": "null"
    }
}