//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnyJob {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnyJob.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Action &quot;{0}&quot; is disabled. 的本地化字符串。
        /// </summary>
        public static string ActionDisabled {
            get {
                return ResourceManager.GetString("ActionDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action exec error. 的本地化字符串。
        /// </summary>
        public static string E00001 {
            get {
                return ResourceManager.GetString("E00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string E00002 {
            get {
                return ResourceManager.GetString("E00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Canceled by user. 的本地化字符串。
        /// </summary>
        public static string E00003 {
            get {
                return ResourceManager.GetString("E00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将值“{0}”转换为类型“{1}”失败。 的本地化字符串。
        /// </summary>
        public static string E00004 {
            get {
                return ResourceManager.GetString("E00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算表达式“{0}”的值发生错误。 的本地化字符串。
        /// </summary>
        public static string E00005 {
            get {
                return ResourceManager.GetString("E00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列化对象“{0}”过程发生错误。 的本地化字符串。
        /// </summary>
        public static string E00006 {
            get {
                return ResourceManager.GetString("E00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反序列化类型“{0}”过程发生错误。 的本地化字符串。
        /// </summary>
        public static string E00007 {
            get {
                return ResourceManager.GetString("E00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从文件“{0}”获取类型“{1}”的对象的过程中发生错误。 的本地化字符串。
        /// </summary>
        public static string E00008 {
            get {
                return ResourceManager.GetString("E00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将对象&quot;{0}&quot;保存到文件&quot;{1}&quot;的过程中发生错误。 的本地化字符串。
        /// </summary>
        public static string E00009 {
            get {
                return ResourceManager.GetString("E00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态求值发生错误。 的本地化字符串。
        /// </summary>
        public static string E00010 {
            get {
                return ResourceManager.GetString("E00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证类型的JsonSchema失败。 的本地化字符串。
        /// </summary>
        public static string E00011 {
            get {
                return ResourceManager.GetString("E00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取动作“{0}”运行时信息发生错误。 的本地化字符串。
        /// </summary>
        public static string E10001 {
            get {
                return ResourceManager.GetString("E10001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取&quot;{0}&quot;的元数据信息发生错误。 的本地化字符串。
        /// </summary>
        public static string E10002 {
            get {
                return ResourceManager.GetString("E10002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务数量达到上限{0}。 的本地化字符串。
        /// </summary>
        public static string E10003 {
            get {
                return ResourceManager.GetString("E10003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未解析出动作“{0}”的名称对象。 的本地化字符串。
        /// </summary>
        public static string E20001 {
            get {
                return ResourceManager.GetString("E20001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未获取到动作“{0}”的运行时对象。 的本地化字符串。
        /// </summary>
        public static string E20002 {
            get {
                return ResourceManager.GetString("E20002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未获取到动作“{0}”的元数据对象。 的本地化字符串。
        /// </summary>
        public static string E20003 {
            get {
                return ResourceManager.GetString("E20003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到动作类型为&quot;{0}&quot;的工厂。 的本地化字符串。
        /// </summary>
        public static string E20004 {
            get {
                return ResourceManager.GetString("E20004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动作&quot;{0}&quot;已经被禁用。 的本地化字符串。
        /// </summary>
        public static string E20005 {
            get {
                return ResourceManager.GetString("E20005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download file &apos;{0}&apos; error, the remote url is &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string E20006 {
            get {
                return ResourceManager.GetString("E20006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid action name &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        public static string InvalidActionName {
            get {
                return ResourceManager.GetString("InvalidActionName", resourceCulture);
            }
        }
    }
}
