{
    "enabled": true,
    "entrypoint": "hello ${name}",
    "kind": "app",
    "inputs": {
        "name": {
            "type": "string"
        }
    },
    "output": {
        "type": "string"
    }
}