{
    "enabled": true,
    "entrypoint": "hello.sh ${name}",
    "kind": "app",
    "inputs": {
        "name": {
            "type": "string"
        }
    },
    "output": {
        "type": "object",
        "properties": {
            "output": {
                "type": "string",
                "description": "The process output content."
            },
            "exitCode": {
                "type": "integer",
                "description": "The process exit code. Nonzero return when has error."
            }
        }
    }
}