{

    "description": "add from node",
    "entrypoint": "add,run",
    "kind": "node",
    "inputs": {
        "num1": {
            "type": "number",
            "must": true
        },
        "num2": {
            "type": "number"
        }
    },
    "output": {
        "type": "number"
    }
}