{

    "description": "add from node",
    "entrypoint": "AnyJob.NetCore.Demo.dll,AnyJob.NetCore.Demo.Static,Add",
    "kind": "netcore",
    "inputs": {
        "num1": {
            "type": "number"
        },
        "num2": {
            "type": "number"
        }
    },
    "output": {
        "type": "number"
    }
}