{
    "enabled": true,
    "description": "add from node",
    "entrypoint": "AnyJob.NetCore.Demo.dll,AnyJob.NetCore.Demo.ValueTaskResult,Concat",
    "kind": "netcore",
    "inputs": {
        "a": {
            "type": "string"
        },
        "b": {
            "type": "string"
        }
    },
    "output": {
        "type": "string"
    }
}