{

    "description": "hello action",
    "entrypoint": "AnyJob.NetCore.Demo.dll,AnyJob.NetCore.Demo.ValueTaskResult,Hello",
    "kind": "netcore",
    "inputs": {
        "name": {
            "type": "string"
        }
    },
    "output": {
        "type": "null"
    }
}