//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnyJob.Runner.NetCore.Wrapper {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCode() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnyJob.Runner.NetCore.Wrapper.ErrorCode", typeof(ErrorCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Load assembly &apos;{0}&apos; failure. 的本地化字符串。
        /// </summary>
        internal static string E400121 {
            get {
                return ResourceManager.GetString("E400121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not reslove type &apos;{0}&apos; in assembly &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string E400122 {
            get {
                return ResourceManager.GetString("E400122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate method &apos;{0}&apos; in type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string E400123 {
            get {
                return ResourceManager.GetString("E400123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find method &apos;{0}&apos; in type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string E400124 {
            get {
                return ResourceManager.GetString("E400124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read inputfile error, the file path is &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string E400125 {
            get {
                return ResourceManager.GetString("E400125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not convert parameter &apos;{0}&apos; value. 的本地化字符串。
        /// </summary>
        internal static string E400126 {
            get {
                return ResourceManager.GetString("E400126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoke action method error. 的本地化字符串。
        /// </summary>
        internal static string E400127 {
            get {
                return ResourceManager.GetString("E400127", resourceCulture);
            }
        }
    }
}
